data_dir: "C:/T.Faisal/OFFICE/mlops-pipeline/storage/data-warehouse/version 1/"
num_classes: 2
class_names: ['cat', 'dog']
# mlflow
mlflow_experiment_name: 'Experiment 1'
mlflow_run_name: 'Version 1'
mlflow_tracking_uri: 'file:C:/T.Faisal/OFFICE/mlops-pipeline/mlruns'
artifact_path: "C:/T.Faisal/OFFICE/mlops-pipeline/storage/artifact"