data_dir: "./storage/data-warehouse/version 1/"
num_classes: 2
class_names: ['cat', 'dog']
# mlflow
mlflow_experiment_name: 'Experiment 1'
mlflow_run_name: ''
mlflow_tracking_uri: 'file:./mlruns'
artifact_path: "./storage/artifact"