#change directory to ...storage/mnist for training with mnist
data_dir: "/home/rsa-hypetune/MLOps-Basic-Pipeline/storage/cat_dog/data-warehouse/version 1"
# paths and directories
result_dir: "/home/rsa-hypetune/MLOps-Basic-Pipeline/results"
train_dir: "./storage/train"
valid_dir: "/storage/valid"
test_dir: "/storage/test"
num_classes: 2 # num_classes: 10 #for mnist 
class_names: ['cat', 'dog']
# class_names: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'] #for mnist

image_height: 227
image_width: 227
num_channels: 3
# model version
## follow this versioning rule 
### cnn -> 1.0.
### alexnet -> 2.0.
### resnet -> 3.0.
### inception -> 4.0.
version: '1.0.1'
# mlflow
mlflow_experiment_name: 'Alexnet'
mlflow_run_name: 'Experiment 10'
mlflow_tracking_uri: "file:/home/rsa-hypetune/MLOps-Basic-Pipeline/mlruns"
artifact_path: "/home/rsa-hypetune/MLOps-Basic-Pipeline/storage/artifact"
