<<<<<<< Updated upstream:pipelines/model/params/config.yaml
data_dir: "/mnt/c/Users/BS505/GitHub_Desktop/test/MLOps-Basic-Pipeline/storage/data-warehouse/version 1"
# paths and directories
result_dir: '/mnt/c/Users/BS505/GitHub_Desktop/test/MLOps-Basic-Pipeline/results'
train_dir: "./storage/train"
valid_dir: "/storage/valid"
test_dir: "/storage/test"
num_classes: 2
class_names: ['cat', 'dog']
image_height: 227
image_width: 227
num_channels: 3
# model version
## follow this versioning rule 
### cnn -> 1.0.
### alexnet -> 2.0.
### resnet -> 3.0.
### inception -> 4.0.
version: '1.0'
# mlflow
mlflow_experiment_name: 'Experiment 1'
mlflow_run_name: ''
mlflow_tracking_uri: 'file:/mnt/c/Users/BS505/GitHub_Desktop/test/MLOps-Basic-Pipeline/mlruns'
=======
data_dir: "/mnt/c/Users/BS505/GitHub_Desktop/test/MLOps-Basic-Pipeline/storage/data-warehouse/version 1"
# paths and directories
result_dir: '/mnt/c/Users/BS505/GitHub_Desktop/test/MLOps-Basic-Pipeline/results'
train_dir: "./storage/train"
valid_dir: "/storage/valid"
test_dir: "/storage/test"
num_classes: 2
class_names: ['cat', 'dog']
image_height: 227
image_width: 227
num_channels: 3
# model version
## follow this versioning rule 
### cnn -> 1.0.
### alexnet -> 2.0.
### resnet -> 3.0.
### inception -> 4.0.
version: '1.0'
# mlflow
mlflow_experiment_name: 'Experiment 1'
mlflow_run_name: ''
mlflow_tracking_uri: 'file:/mnt/c/Users/BS505/GitHub_Desktop/test/MLOps-Basic-Pipeline/mlruns'
>>>>>>> Stashed changes:pipelines/dags/model/params/config.yaml
artifact_path: "/mnt/c/Users/BS505/GitHub_Desktop/test/MLOps-Basic-Pipeline/storage/artifact"