# paths and directories
#change directory to ...storage/mnist for training with mnist
data_dir: "/home/rsa-hypetune/MLOps-Basic-Pipeline/storage/cat_dog/data-lake/test"

num_classes: 2
class_names: ['cat', 'dog']
image_height: 227
image_width: 227
num_channels: 3
# model version
## follow this versioning rule 
### cnn -> 1.0.
### alexnet -> 2.0.
### resnet -> 3.0.
### inception -> 4.0.
version: '1.0'
# mlflow
mlflow_experiment_name: 'Alexnet'
mlflow_run_name: 'Experiment 1'
mlflow_tracking_uri: 'file:/home/rsa-hypetune/MLOps-Basic-Pipeline/mlruns'
#change directory to ...storage/mnist for training with mnist
artifact_path: "/home/rsa-hypetune/MLOps-Basic-Pipeline/storage/cat_dog/artifact"
