# paths and directories
data_dir: "/Documents/RnDLab/mlops-deep-nn/MLOps-Basic-Pipeline/storage/data-lake/test"

num_classes: 2
class_names: ['cat', 'dog']
image_height: 227
image_width: 227
num_channels: 3
# model version
## follow this versioning rule 
### cnn -> 1.0.
### alexnet -> 2.0.
### resnet -> 3.0.
### inception -> 4.0.
version: '1.0'
# mlflow
mlflow_experiment_name: 'Experiment 1'
mlflow_run_name: ''
mlflow_tracking_uri: 'file:/Documents/RnDLab/mlops-deep-nn/MLOps-Basic-Pipeline/mlruns'
artifact_path: "/Documents/RnDLab/mlops-deep-nn/MLOps-Basic-Pipeline/storage/artifact"